### ISSUE TITLE
Stitches can generate it's own types, no need for duplication

### ISSUE THREAD

**Issue by andrewdoro** [diegosilvatech/awesome-stitches-template#1]
Stitches has implemented different ways to infer the types such as `Stitches.VariantProps<>`.  The issue with this is that you lose auto-infer of params for storybook.
There is a workaround using this snippet:
https://gist.github.com/f1lander/db2a9a95a4442e1e98217001ab724d3f

https://github.com/diegosilvatech/awesome-template-stitches/blob/9086dc1c2d414e77cb219746a53df88c9730a4d3/src/components/button/Button.tsx#L3-L16

**Comment by odiegorsilva** [comment]
Hi @andrewdoro. Thanks for this Issue.

I will check this issue soon. At the moment Storybook can interpret all the properties of my component automatically and everything seems to work as expected.

At the moment this is a side project and things can take a little time, but if you prefer, you can open a PR with your proposal.
